apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "helper.common-labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      {{- include "helper.common-labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helper.common-labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
          name: {{ .Values.ports.name }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.limits.cpu | quote }}
            memory: {{ .Values.limits.memory | quote }}
          requests:
            cpu: {{ .Values.requests.cpu | quote }}
            memory: {{ .Values.requests.memory | quote }}
        volumeMounts:
        - mountPath: {{ .Values.volumeMountPath }}
          name: {{ .Values.volumeName }}
      volumes:
      - name: {{ .Values.volumeName }}
        emptyDir: {}
