name: Create AWS Secrets

on:
  workflow_dispatch: {}

env:
  AWS_REGION: us-west-2

jobs:
  create-secrets:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq
    
    - name: Create individual secrets from JSON
      run: |
        JSON_CONTENT=$(cat secrets.json)
        echo "$JSON_CONTENT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
          echo "Creating secret: $key"
          
          aws secretsmanager create-secret \
            --name "$key" \
            --description "Secret for $key created via GitHub Actions" \
            --secret-string "$value" \
            --region ${{ env.AWS_REGION }} || \
          aws secretsmanager update-secret \
            --secret-id "$key" \
            --secret-string "$value" \
            --region ${{ env.AWS_REGION }}
            
          echo "✅ Secret $key created/updated successfully"
        done
