name: helm-deploy

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on:
      - ubuntu-latest
    
    strategy:
      fail-fast: true

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Helm tool installer
      uses: Azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Check Helm Template
      run: |
        cd ./grafana-alloy
        helm template .
