name: helm-deploy

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    env:
      GCP_PROJECT: damontargaryen-project
      
    runs-on:
      - ubuntu-latest
    
    strategy:
      fail-fast: true

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Helm tool installer
      uses: Azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Setup gCloud
      uses: google-github-actions/setup-gcloud@v2.1.3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2.1.4
      with:
        credentials_json: ${{ secrets.GCP_KEY }}

    - name: List GCP Config
      run: |
        gcloud auth list
        gcloud config list

    - name: Check Helm Template
      run: |
        cd ./grafana-alloy
        helm template .
